const S={products:'Produtos',units:'Unidades',movements:'Movimentacoes',stock:'Estoque_Atual',inventories:'Inventarios',expiries:'Validades',sales:'Vendas'};
function setupOKEO(){const ss=SpreadsheetApp.getActive();ens_(ss,S.products,['EAN','Produto','Fabricante','Categoria','NCM','CEST','EAN adicional','Fornecedor','Ativo']);ens_(ss,S.units,['Unidade','Tipo','Ativa']);ens_(ss,S.movements,['ID','DataHora','Tipo','Origem','Destino','EAN','Produto','Quantidade','CustoUnitario','Motivo']);ens_(ss,S.stock,['Unidade','EAN','Produto','Quantidade','CustoMedio','AtualizadoEm']);ens_(ss,S.inventories,['ID','DataHora','Unidade','EAN','Produto','Quantidade']);ens_(ss,S.expiries,['ID','DataHora','Unidade','EAN','Produto','Validade','Quantidade']);ens_(ss,S.sales,['ID','DataHora','Unidade','EAN','Produto','Quantidade','ValorVenda','CustoUnitario']);}
function ens_(ss,n,h){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(h);return sh}
function doGet(e){return j_(master_())}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}');if(b.action==='movement'){move_(b.data);return j_({ok:true})}return j_({ok:false,error:'acao'})}catch(x){return j_({ok:false,error:String(x)})}}
function master_(){const ss=SpreadsheetApp.getActive(),p=rows_(ss.getSheetByName(S.products)).filter(r=>r[8]!==false).map(r=>({ean:String(r[0]||''),produto:r[1]||'',fabricante:r[2]||'',categoria:r[3]||'',ncm:r[4]||'',cest:r[5]||'',ean_adicional:r[6]||'',fornecedor:r[7]||''})).filter(x=>x.ean),u=rows_(ss.getSheetByName(S.units)).filter(r=>r[2]!==false).map(r=>String(r[0]||'')).filter(Boolean);return {products:p,units:u}}
function move_(m){const ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(S.movements);sh.appendRow([m.id||Utilities.getUuid(),new Date(m.date||Date.now()),m.type||'',m.from||'',m.to||'',String(m.ean||''),m.product||'',Number(m.qty||0),Number(m.unitCost||0),m.reason||'']);stock_(m)}
function stock_(m){const sh=SpreadsheetApp.getActive().getSheetByName(S.stock),q=Number(m.qty||0),c=Number(m.unitCost||0),e=String(m.ean||'');if(m.type==='TRANSFERENCIA'){const ac=avg_(sh,m.from,e)||c;dec_(sh,m.from,e,q);inc_(sh,m.to,e,m.product,q,ac)}else if(m.type==='ENTRADA_COMPRA'||m.type==='AJUSTE_POSITIVO')inc_(sh,m.to||m.from,e,m.product,q,c);else dec_(sh,m.from||m.to,e,q)}
function row_(sh,u,e){const v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(u)&&String(v[i][1])===String(e))return i+1;return 0}
function avg_(sh,u,e){const r=row_(sh,u,e);return r?Number(sh.getRange(r,5).getValue()||0):0}
function inc_(sh,u,e,p,q,c){if(!u)return;let r=row_(sh,u,e);if(!r){sh.appendRow([u,e,p,q,c,new Date()]);return}const oq=Number(sh.getRange(r,4).getValue()||0),oc=Number(sh.getRange(r,5).getValue()||0),n=oq+q,a=(q>0&&c>0&&n>0)?((oq*oc)+(q*c))/n:oc;sh.getRange(r,4,1,3).setValues([[n,a,new Date()]])}
function dec_(sh,u,e,q){if(!u)return;const r=row_(sh,u,e);if(!r)return;const oq=Number(sh.getRange(r,4).getValue()||0);sh.getRange(r,4).setValue(Math.max(0,oq-q));sh.getRange(r,6).setValue(new Date())}
function rows_(sh){if(!sh||sh.getLastRow()<2)return [];return sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).getValues()}
function j_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
